### ISSUE TITLE
Add option for lowercase hex

### ISSUE THREAD

**Issue by ovanbiervliet** [superhighfives/pika#10]
It's a user preference alright, but the ascenders make the values more readable too :)

#ab83b1 vs #AB83B1

**Comment by superhighfives** [comment]
Good catch, and agreed on readabillity. Will do. Thanks for the thoughtful feedback, too, @ovanbiervliet. 👍

**Comment by superhighfives** [comment]
This is also fixed in: https://github.com/superhighfives/pika/releases/tag/0.0.8-beta2
