### ISSUE TITLE
Report color while hovering

### ISSUE THREAD

**Issue by tsheiner** [superhighfives/pika#100]
**Is your feature request related to a problem? Please describe.**
Not a problem, mild inconvenience

**Describe the solution you'd like**
If I have the selector cursor turned on, I'd like the foreground color panel to divide in to two regions, one reports the current selected foreground color, the other reports the color of the pixel over which I am currently hovering. Selection behavior remains the same--selected foreground color doesn't change if and until I click, but I gain the ability to compare my current selection to current hover position color.

**Comment by superhighfives** [comment]
Thanks so much for taking the time to write this up, @tsheiner—really appreciate it. Unfortunately things are limited by the API Pika is currently using—`[nscolorsampler](https://developer.apple.com/documentation/appkit/nscolorsampler)`. It doesn't allow any customisation currently. If Apple adds customisation options to it, I'd love to do more with the display of the current colour vs hovered, etc. Fingers crossed, one day.
