### ISSUE TITLE
Find closest accessible color

### ISSUE THREAD

**Issue by T04435** [superhighfives/pika#103]
**Is your feature request related to a problem? Please describe.**
No way to solve the fail compliance check

**Describe the solution you'd like**
When compliance fails on any range(Normal/Large => AA/AAA)

<img width="458" alt="screencapture" src="https://github.com/superhighfives/pika/assets/10654469/f37aa6ca-4b3e-46a9-b535-2afeca14ed49">

Add an action to find closes color to fix it, IE click on Normal AAA, that gives me a menu to find closest compliant color

**Describe alternatives you've considered**
Manually find another color

**Additional context**

**Comment by superhighfives** [comment]
You can now tweak colours until you get a result that passes. It's currently in beta, but you can grab it via the app or at https://github.com/superhighfives/pika/releases/tag/0.0.18-beta2. See more on #125.
