### ISSUE TITLE
Option to hide the menu bar icon

### ISSUE THREAD

**Issue by bikrrr** [superhighfives/pika#11]
**Is your feature request related to a problem? Please describe.**
No problem, other than my OCD and wanting to minimize the number of icons in my Mac menu bar.

**Describe the solution you'd like**
An option in preferences that allows me to hide the menu bar icon, but leave the app running so I can access it via keyboard shortcut. And if possible, support the ability to Cmd + drag it off in Big Sur. Though that may be reserved for functionality in Control Center (sound, Bluetooth, etc.).

**Describe alternatives you've considered**
Not looking at it. ;)

**Additional context**

**Comment by superhighfives** [comment]
Seems reasonable! Added to the roadmap—thanks for flagging, @bikrrr. 👍 

Will check on the Cmd + drag, too.

**Comment by superhighfives** [comment]
Hey @bikrrr—this is now available in the latest beta, 0.0.8-beta1. You can download it here:
https://github.com/superhighfives/pika/releases/tag/0.0.8-beta1

I'd really appreciate it if you could check it out and let me know if you see any issues. (And if you do, you can always fall back to the latest stable version.) The option is in the preferences menu, and there additional keyboard shortcuts—⌘D and ⇧⌘D to trigger the foreground and background picker, and ⌘C and ⇧⌘C to copy the foreground and background, respectively.

**Comment by superhighfives** [comment]
Ah, spoke too soon—there's a bug with 0.0.8-beta1 where the footer won't update. Fixed in 0.0.8-beta2. You can either enable beta updates and check for updates in the app, to grab it here: https://github.com/superhighfives/pika/releases/tag/0.0.8-beta2

**Comment by bikrrr** [comment]
Wow, you're fast! 

I installed 0.0.8-beta2 and everything seems to be working well and the menu option works as expected. Nice! 🙌

**Comment by superhighfives** [comment]
Aw, cheers @bikrrr. One thing to flag—I was keen to hide the menu on Apple + drag, but that setting is managed external to the app defaults, which makes it more challenging to turn it on and off again in preferences, so stuck with preferences for now.

If anyone comes across this and can think of a clever way to manage it, PR's are very welcome. 😊
