### ISSUE TITLE
Open picker when the app is launched

### ISSUE THREAD

**Issue by franciscolourenco** [superhighfives/pika#113]
**Is your feature request related to a problem? Please describe.**
Currently, when Pika is launched in Dock mode, the color picker windows doesn't automatically open. It is necessary to click on the dock icon a second time.
Use-case: I would like to open the app, use it and close it, without having to run it permanently in the background. 

**Describe the solution you'd like**
I would like for Pika to automatically show the color picker when it is launched, at least when in Dock mode.

**Comment by superhighfives** [comment]
Thanks for adding this, @franciscolourenco! I had used the global shortcut to achieve this (you can set it in your preferences) so from the time Pika is open, you simply trigger the shortcut and start picking, and the app will appear. Curious if this would meet your requirement?

**Comment by franciscolourenco** [comment]
@superhighfives my intent was to avoid having Pika running always in the background. Launch the app, pick color, close app.

**Comment by superhighfives** [comment]
I hear you, @franciscolourenco. I believe you should be able to do that with the global shortcut—open Pika, trigger global shortcut, pick the colour, copy it, quit Pika. That's how I use it personally. I'm reticent to change the default behaviour, but adding a setting for "Show Pika on launch" could also be an option. 🤔

**Comment by franciscolourenco** [comment]
@superhighfives a setting like that would be great, so that you don't have to use an extra keyboard shortcut.

**Comment by superhighfives** [comment]
Great. Flagged this as help wanted in case anyone wants to take a pass at adding this feature. 👍

**Comment by superhighfives** [comment]
This is now released as `0.0.17-beta1`, which you can download from https://github.com/superhighfives/pika/releases/tag/0.0.17-beta1, or by checking "Subscribe to beta releases" in Pika's settings and then "Check for updates..." in the menu. Thanks @franciscolourenco, appreciate it!

Any feedback or issues, please let me know.

**Comment by franciscolourenco** [comment]
Works, thank you @superhighfives ❤️
