### ISSUE TITLE
Paste color in differend format

### ISSUE THREAD

**Issue by Hydro8** [superhighfives/pika#114]
**Is your feature request related to a problem? Please describe.**
I use color picker with different app at my work. Sometime I need a color in RGB format and sometime in hex format.

**Describe the solution you'd like**
Coming from windows, I used share X where I opened color picker, click to copy color un rgb format or alt + click to copy color in hex format.

By the way, thanks for your great app :)

**Comment by superhighfives** [comment]
Ooooh, thanks for the suggestion @Hydro8. So you're thinking some kind of modifier key (for example, `Control + Command + c`) to get different formats independently of what you've got selected in the UI? Were you thinking that this specifically would be handled by a modifier key?

**Comment by Hydro8** [comment]
Yes something like that. 

Or maybe it’s possible to handle this when we click on the screen : 
- I use a shortcut to launch color picker. 
- If I click on screen I have color on regex format. 
- If I cmd (or another modifier) + click, I have color on RVB format.

**Comment by superhighfives** [comment]
Unfortunately Apple's API for grabbing colours from the screen (without needing complex and privacy adverse permissions to be granted) is pretty limited: https://developer.apple.com/documentation/appkit/nscolorsampler

I'm not aware of any way to differentiate types of clicks or shortcuts when using the Apple API. If anything changes on that front I'd love to implement more options for the colour picker interface (showing the colour inline in the picker, allowing different "types" of picking with keyboard shortcuts etc.

**Comment by Hydro8** [comment]
Ok I understand. So maybe use a modifier key.

**Comment by superhighfives** [comment]
One other thought is that maybe PIka could have a shortcut to move between hex, rgb, hsb and hsl. Possibly `Command + 1`, `Command + 2`, etc. 🤔 

Will keep this one open to see if it resonates with others. Also if anyone wants to take a pass at it, I'd love to check out a PR. 👍

**Comment by Hydro8** [comment]
What do you think of adding deeplink to pika ?

Like "pika://pick/hex" to pick in Hex format "pika://pick/rgb"...

That's way we can use our own shortcut app and we. can use pika with other apps like raycast.

**Comment by superhighfives** [comment]
Ooooh, I love this idea. I'd also love to add keyboard shortcuts to move between colour formats. Will take a look, try and get something beta. 👍

**Comment by Hydro8** [comment]
Nice thanks a lot for considering this :)

**Comment by superhighfives** [comment]
This is now released as `0.0.17-beta1`, which you can download from https://github.com/superhighfives/pika/releases/tag/0.0.17-beta1, or by checking "Subscribe to beta releases" in Pika's settings and then "Check for updates..." in the menu. Thanks @Hydro8, hope it helps!

Any feedback or issues, please let me know.

**Comment by superhighfives** [comment]
Also, the list of URL schemes is here: https://github.com/superhighfives/pika/tree/0.0.17?tab=readme-ov-file#url-triggers

**Comment by Hydro8** [comment]
Thanks a lot ! The url scheme works well by itself.

However, I can't make it work with raycast quicklinks sadly. 
When I choose to open the quicklink with arc, it worked but it's slow because it must open arc fist.
When I choose to open it with pika directly ,nothing happen.

**Comment by superhighfives** [comment]
Would you mind sharing yours?

**Comment by Hydro8** [comment]
I tried your setup but nothing happen.
Before , I use the same setup as you, without the variable.

**Comment by superhighfives** [comment]
Hmmm, I've tried it on two set ups now, seems to be working as expected. I wonder if someone else would be able to give it a shot? Just to confirm, you're definitely running the latest version—just thinking if an older version is somehow running at the same time it might be clashing. You can double check your activity monitor here:

<img width="852" alt="image" src="https://github.com/superhighfives/pika/assets/449385/c588976d-25fc-4df6-a996-42effbc9b27e">

And the version is available in About:

<img width="618" alt="image" src="https://github.com/superhighfives/pika/assets/449385/d35df947-7c0b-4b88-bf69-9090b172fa83">

**Comment by Hydro8** [comment]
Ok I reinstall pika beta and raycast and it works nice now ! Well done, thanks a lot !

Last thing to imprive my workflow, will it be possible to add format to deeplink ?

Like "pika://pick/rgb/background" or "pika://pick/hex/background". Or even shorter "pika://rgb/background".

**Comment by superhighfives** [comment]
Yeah, for sure—I started looking into it when I was pulling this together. I'm keen to explore that for `0.0.17-beta2`. Thanks for flagging.

**Comment by superhighfives** [comment]
Alrighty, got this working for `0.0.17-beta2`. As there hasn't been any other feedback I'll release it shortly.

**Comment by superhighfives** [comment]
Aaaaand it's released as `0.0.17-beta2`, which you can download from https://github.com/superhighfives/pika/releases/tag/0.0.17-beta2, or by checking "Subscribe to beta releases" in Pika's settings and then "Check for updates..." in the menu. Thanks @Hydro8.

Any feedback or issues, please let me know.

**Comment by Hydro8** [comment]
Hell yeah ! Very nice !

Thanks a lot @superhighfives, I really like your app and it's even better for my workflow.

Thanks again for adding these features quickly.
