### ISSUE TITLE
Colors aren't accurate

### ISSUE THREAD

**Issue by bastianfbr** [superhighfives/pika#116]
**Describe the bug**
Found colors aren't accurate

**To Reproduce**
1.  Pick a color

**Expected behavior**
Give the right color

**Screenshots**
<img width="483" alt="image" src="https://github.com/superhighfives/pika/assets/29505634/d258663d-51ec-4970-aa0b-115c592b7d4d">

**Environment (please complete the following information):**
 - OS: MacOS 14.2.1
 - App Version: Build 34
 - Architecture: Apple Silicon

**Additional context**

I work with Figma and i'm making a website. Colors aren't accurate with the color picker and that's bizarre.

**Comment by superhighfives** [comment]
Hey @bastianfbr—welcome to [the complex world of colour spaces](https://blog.frame.io/2020/02/03/color-spaces-101/). There can be differences between the colour space your operating system is working in, and the colour space a piece of design software uses. Fortunately, you can change the colour space within Pika in the Settings. That can hep you to align it to the design software you're using, [like Figma](https://help.figma.com/hc/en-us/articles/360039825114-Manage-color-profiles-in-design-files).

Thanks for raising the issue. 👍
