### ISSUE TITLE
Support invoking colour picking via URI or scripting

### ISSUE THREAD

**Issue by NeighNeighNeigh** [superhighfives/pika#122]
**Is your feature request related to a problem? Please describe.**
I would like to invoke Pika's colour picking mode via my 2 primary automation tools (Alfred and Kando Pie Menu). If I'm not mistaken, the only way to invoke this currently is by assigning a hotkey. This is undesirable as I find assigning and maintaining hotkeys can get messy, especially with lots of automations at play.

**Describe the solution you'd like**
It would be nice if I could invoke PIKA's picking mode via URI, shell scripting or AppleScript.

Thanks so much for PIKA, it's truly delightful!

**Comment by superhighfives** [comment]
Hey @NeighNeighNeigh—thanks for the kind words. You should be able to call Pika via automation tools with the URL triggers. There's a full list here: https://github.com/superhighfives/pika?tab=readme-ov-file#url-triggers

I've only personally used this with Raycast, but it should work with any quick link type set up:

<img width="862" alt="image" src="https://github.com/superhighfives/pika/assets/449385/d3129970-fb8f-4c04-80ff-55cdfb9f65fe">

**Comment by NeighNeighNeigh** [comment]
Oh I’m mortified 😅
It’s already possible, exactly what I need, and clearly documented!
Thank you and apologies for being daft!
