### ISSUE TITLE
Configurable size and zoom of the picker

### ISSUE THREAD

**Issue by Stanko** [superhighfives/pika#130]
First, I want to thank you for making and maintaining pika, it is a nice piece of software!

**Is your feature request related to a problem? Please describe.**
Picker feels small and it is zoomed in a lot. Sometimes it is hard to pinpoint the pixel I want to pick.

**Describe the solution you'd like**
It is not really a problem, but I think it would be a quality of life enhancement to have size of the picker and zoom level configurable. Personally I would ~increase the default picker at least twice~ decrease the zoom level at least twice.

Here is my proposed solution, next to the screenshot of the current behavior (I would keep the color label, I just didn't mock it):
|Current|Example 4x|Example 8x|
|-|-|-|
|![current](https://github.com/user-attachments/assets/560183f5-8909-4e5a-95ff-cc5016c92145)|![4x](https://github.com/user-attachments/assets/f70f3983-0522-4e9c-b5ab-1af0b11a5b00)|![8x](https://github.com/user-attachments/assets/afa9c73a-c4a9-43c3-a3ed-9a30a96cad79)|

I think this gives a little bit more context when picking colors.

Ideally these would be included in the settings. I have no idea how much work this is (as I don't know Swift), but I'm willing to try making it if you can point me to the correct files.

**Comment by superhighfives** [comment]
I would love to be able to do this, but currently I'm using Apple's [nscolorsampler](https://developer.apple.com/documentation/appkit/nscolorsampler), which has no options. Hopefully in future they'll open it up, because the trade off is to get permission to record the user's screen, which I don't want to do.

Thanks so much for taking the time to suggest this, and hopefully the API will developer in future such that this will be possible.

**Comment by Stanko** [comment]
Thanks for the fast response! Ah I see, and I agree it is smart not to ask for the screen recording permission.

I might try to use "Key-Value coding" to hack my way around NSColorSampler lack of APIs. Something like
```swift
sampler.setValue(zoom, forKey: "magnification")
```
No idea if that will work, but if it does, would you consider merging a feature like that (under experimental flag in settings or )? I'll completely understand if you don't want something like that in your codebase.

Cheers!

**Comment by superhighfives** [comment]
Thanks for the suggestion, @Stanko! Tried the above and got:
```
Exception	NSException *	"[<NSColorSampler 0x600000911e80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key magnification."	0x0000600000795d70
```

Not sure if there's another way, but if you come across something I'm happy to give it a shot.

**Comment by Stanko** [comment]
Thank you for trying it! It was a long shot. Cheers!
