### ISSUE TITLE
Swap colors button is jumping

### ISSUE THREAD

**Issue by abinesan** [superhighfives/pika#132]
**Describe the bug**
The swap colours button jumps right and leaves.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Menu bar'
2. Click on 'the Pika icon.'
3. Hover the 'Swap button'

**Expected behaviour**
Button without jumping right and left.

**Screenshots**
Screen recording added

**Environment (please complete the following information):**
 - OS: macOS 15.2 Beta (24C5079e)
 - App Version: Version 0.0.18-beta2
 - Architecture: Apple Silicon

**Additional context**
--

https://github.com/user-attachments/assets/960c80c0-9749-405c-ad25-d79143513099

**Comment by superhighfives** [comment]
Fix going out in `0.0.18-beta3`. 👍
