### ISSUE TITLE
Pika remains in Dock even when set to Menu bar only (Sequoia)

### ISSUE THREAD

**Issue by heitorgn** [superhighfives/pika#137]
**Describe the bug**
Even after configuring the app to show only in the Menu Bar, it continues to appear in the Dock.
Only when selecting in "App Settings": Show in Dock and then Menu Bar again, it disappears from the Dock.

**To Reproduce**
1. Select "Show in menu bar" in App Settings
2. Close Settings and Pika window
3. Open Pika and use it normally
4. Pika will appar on Dock and stay there
5. Close window and Pika stays there
6. Open Pika and go to Settings again
7. Switch between "Dock" and "Menu bar" again
8. Now icon is gone from Dock

**Expected behavior**
Pika icon should not appear in the Dock if "Show in menu bar" option is selected

**Environment (please complete the following information):**
 - OS: Sequoia 15.2 (24C101)
 - App Version: 1.0.0 (Build 48)
 - Architecture: Apple Silicon (MBP M3Pro)

**Comment by superhighfives** [comment]
Thanks for flagging, @heitorgn. How are you re-opening Pika? Are you clicking the icon in the menu bar, or using a launcher like spotlight or Raycast?

**Comment by heitorgn** [comment]
I have a shortcut in Raycast, because I like to open the entire Pika window
with the colors and Contrast Ratio instead of using the app's shortcut that
only invokes the color picker.

If you added this option to the App it would be great. I wouldn't need
Raycast to trigger the App.

Regards,

*Heitor Garcia*


Em qua., 18 de dez. de 2024 às 17:03, Charlie Gleason <
***@***.***> escreveu:

**Comment by superhighfives** [comment]
Yep, was able to recreate with Raycast. Will take a look.

On the shortcut, how would you imagine that working? I'm keen to understand this bit:
> open the entire Pika window with the colors and Contrast Ratio

Do you have a screenshot I could check out?

**Comment by heitorgn** [comment]
Sure, it's like this:

When using Pika's Global Shortcut:
[image: image.png]
The Cursor becomes this color picker, which is a magnifying glass circle
with the collection pixel in the middle

But when I use the shortcut created in Raycast to open the Pika application:
[image: image.png]
This Pika window opens:
[image: image.png]

And with this window opened I can click on the Foreground or Background to
start picking colors and keep an eye on Contrast Ratio, Compliance etc.
It's much better for me than the solo magnifying color picker and no info.

So the ideal (IMO) would be to have two shortcuts in the app, one for the
collection directly (current) and another to show the app window with the
background and foreground colors...

Regards,

*Heitor Garcia*


Em qua., 18 de dez. de 2024 às 18:30, Charlie Gleason <
***@***.***> escreveu:

**Comment by heitorgn** [comment]
Sure, it's like this:

When using Pika's Global Shortcut:
![](https://i.imgur.com/rxlAjxr.png)
The Cursor becomes this color picker, which is a magnifying glass circle
with the collection pixel in the middle

But when I use the shortcut created in Raycast to open the Pika application:
![](https://i.imgur.com/jRNJmlZ.png)
This Pika window opens:
![](https://i.imgur.com/aPSvifC.png)

And with this window opened I can click on the Foreground or Background to
start picking colors and keep an eye on Contrast Ratio, Compliance etc.
It's much better for me than the solo magnifying color picker and no info.

So the ideal (IMO) would be to have two shortcuts in the app, one for the
collection directly (current) and another to show the app window with the
background and foreground colors...

**Comment by superhighfives** [comment]
Great, a fix for this bug has gone out for 1.0.1. 😊 Thanks for flagging!

Appreciate the feedbackl, too. For me I tend to use Command+space (for Raycast) and type `Pi` to get the window back. I also think using a custom shortcut like what you've set up makes sense too.
