### ISSUE TITLE
Add a button to swap background and foreground

### ISSUE THREAD

**Issue by superhighfives** [superhighfives/pika#25]

**Comment by johalv** [comment]
I would love to see this! 👍

**Comment by superhighfives** [comment]
Thanks @johalv—starting digging into how this might work tonight. 👍 Thinking of including it in a future beta, so will keep this issue updated.

**Comment by superhighfives** [comment]
Shipped with https://github.com/superhighfives/pika/releases/tag/0.0.9 🎉 Thanks for the original suggestion, @dizzyup. 🙌
