### ISSUE TITLE
History / data store

### ISSUE THREAD

**Issue by superhighfives** [superhighfives/pika#26]

**Comment by AClmbr** [comment]
Core Data is a built-in persistence framework, quite powerful according to me. Do you have an idea of which data you want to store?

**Comment by superhighfives** [comment]
Hey @AClmbr! Yeah, I've experimented a little with Core Data, which seems like a great fit. Initially I was thinking the ability to undo / redo actions (color picking and swapping come to mind, primarily) and later on, being able to open a window showing a full color history, potentially in a two column layout:

![Frame 39](https://user-images.githubusercontent.com/449385/111785905-194f0800-88b5-11eb-8d8d-929fa42e32c8.png)

🙌

**Comment by AClmbr** [comment]
Ok great!

For the undo / redo actions, have a look at https://developer.apple.com/documentation/foundation/nsundomanager, it may be useful.

Otherwise I can help you with Core Data, I'm quite familiar with it 👌

**Comment by superhighfives** [comment]
Oh rad, will take a look. Thanks for the pointer on undo. 👍  Thinking of approaching this one after `0.0.11` is done, so I'll let you know how I go.

**Comment by superhighfives** [comment]
Closing this as undo / redo has been added to the app. 👍
