### ISSUE TITLE
Feature request: Easier and faster way to copy the colour code.

### ISSUE THREAD

**Issue by alpower** [superhighfives/pika#3]
Firstly thank you for making this - it's already proving invaluable. 

**Is your feature request related to a problem? Please describe.**
I was wondering whether it's utility as a colour picker could be improved by making getting the colour code onto the clipboard faster - currently, it takes two clicks (right click and click again).

![image](https://user-images.githubusercontent.com/858646/104467049-c81d5200-55ad-11eb-9c96-63b6021a73ab.png)

**Describe the solution you'd like**
Ideally, this could be achieved using both mouse and keyboard. You could include an extra icon to copy the preferred display format to the clipboard from both foreground and background like so:
![image](https://user-images.githubusercontent.com/858646/104468092-f8192500-55ae-11eb-9d83-6531dcbc9e3e.png)

and maybe assign keyboard shortcuts for either as an additional step or allow `Cmd+C` if your mouse is over the Foreground or the Background and Pika app is in focus. I guess the code that would be copied using this shortcut method would be the one displayed on the screen and set in preferences.

Thanks for the consideration, and thanks for making such a useful app!

**Comment by joho** [comment]
+1

**Comment by superhighfives** [comment]
Hey @alpower, @joho—love this idea, and added it to the roadmap. One thing I would love to look at in future is making the text editable as well, so you can paste in your own value on either side. I want that to be really seamless, so it's a little further down the track, but I know I'll need to slightly rethink the layout of the swatches. This could be a good opportunity to consider that now.

One thought is centralising the copy to a single icon, with left and right click. Here's a quick sketch:

![image](https://user-images.githubusercontent.com/449385/104528745-fb88cc80-55ff-11eb-918e-a74b4e379d3c.png)

I think my only concern would be doing it in a way that makes it clear it has a right click, but that could be a part of the onboarding, potentially. Also, you have the ability to change the colour format in preferences, so it's never 100% hidden. 🤔 Also, the keyboard shortcuts would be wild, and there could be some kind of animation on the icon to show that you've triggered it.

One last night—you can right click anywhere on the swatch to get that same menu, in case the tiny button gets frustrating. Bit of an easter egg. 😅 

Thanks for opening the first real issue on here, too. Appreciate it!

**Comment by alpower** [comment]
Thanks for responding and the extra info - I think your suggestions make complete sense, as well as the left/right-click stuff, and I really like the layout suggestion. 💯

**Comment by joho** [comment]
+1

**Comment by meduzen** [comment]
One great way (among others) to propose color copy could be the Touch Bar, like [Contrast](https://contrasteapp.com) does:

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/9340937/104819837-9d8efb80-5830-11eb-931e-e1b6af3626ba.png">

**Comment by superhighfives** [comment]
Thanks @meduzen. I moved your suggestion into a new issue, #14. 👍

**Comment by superhighfives** [comment]
Hey @alpower @clif-os @santicros @lecoueyl @joho—this is now available in the latest beta, 0.0.8-beta1. You can download it here:
https://github.com/superhighfives/pika/releases/tag/0.0.8-beta1

I'd really appreciate it if you could check it out and let me know if you see any issues. (And if you do, you can always fall back to the latest stable version.) The keyboard shortcuts are ⌘D and ⇧⌘D to trigger the foreground and background picker, and ⌘C and ⇧⌘C to copy the foreground and background, respectively.

Planning to tackle redesigning the swatch view separately, so will make a separate issue for that.

**Comment by superhighfives** [comment]
Spoke too soon—there's a bug with 0.0.8-beta1 where the footer won't update. Fixed in 0.0.8-beta2. You can either enable beta updates and check for updates in the app, to grab it here: https://github.com/superhighfives/pika/releases/tag/0.0.8-beta2
