### ISSUE TITLE
Hide Pika when sampling

### ISSUE THREAD

**Issue by ovanbiervliet** [superhighfives/pika#38]
Pika 0.0.9-beta1 build 12 introduces the hiding functionality while color picking. 

Although I like the idea of this, I'd want to see this refined to only work when the mouse is near the Pika window. There are 2 reasons for this:
- Often I want to refer to previously sampled color(s) while picking a new one, e.g. to avoid picking the same color etc.
- Since Pika doesn't currently show the color value near the magnifier, a quick glance to the Pika window helps in picking the right color, when you have to try a few times it gets annoying when the window disappears each time

**Comment by superhighfives** [comment]
Hey @ovanbiervliet. Got a related issue for this one, #31, so going to reference this comment there and close this one. 👍
