### ISSUE TITLE
Colour profile mismatch

### ISSUE THREAD

**Issue by superhighfives** [superhighfives/pika#4]
**Describe the bug**
https://twitter.com/funwithstuff/status/1349556524033556482

**To Reproduce**
Steps to reproduce the behavior: TBA

**Expected behavior**
These values should match:
![image](https://user-images.githubusercontent.com/449385/104616054-c9b84a00-5681-11eb-9313-a9cdecd8862c.png)

**Comment by eddyg** [comment]
Thanks for Pika! For what it’s worth, the built-in [Digital Color Meter](https://support.apple.com/guide/digital-color-meter/welcome/mac) app lets you select the “Color Space” from a drop-down menu, so Pika may need something similar. (I’m not near my Mac right now, otherwise I’d try DCM with the system color picker.)

**Comment by ovanbiervliet** [comment]
Fwiw, on my system they do match. I'm using the correct display profile for my display (Dell U2720Q) and the display was set to sRGB. Other tools like Contrast failed to get it right (and say it can't be done), SIP works fine provided you set the color space accordingly:
<img width="417" alt="CleanShot 2021-01-16 at 17 07 03@2x" src="https://user-images.githubusercontent.com/3488544/104816729-45023300-581d-11eb-8d43-1d7c2208d15e.png">

**Comment by superhighfives** [comment]
Started on this one—looking at moving to https://github.com/yannickl/DynamicColor, rather than my cobbled together collection of extensions and methods.

**Comment by superhighfives** [comment]
Hey @eddyg—this is now available in the latest beta, 0.0.8-beta1. You can download it here:
https://github.com/superhighfives/pika/releases/tag/0.0.8-beta1

I'd really appreciate it if you could check it out and let me know if you see any issues. (And if you do, you can always fall back to the latest stable version.) Color spaces are in the preferences menu, and there additional keyboard shortcuts—⌘D and ⇧⌘D to trigger the foreground and background picker, and ⌘C and ⇧⌘C to copy the foreground and background, respectively.

**Comment by eddyg** [comment]
I did a quick test, and when changing the color space preference in Pika between sRGB and Adobe RGB, the values match what is displayed by Digital Color Meter. 👍 

Unrelated: it seems like the contrast ratio no longer updates?

**Comment by superhighfives** [comment]
Ah, good catch, @eddyg. Thanks for flagging. Fixed in 0.0.8-beta2. You can either enable beta updates and check for updates in the app, to grab it here: https://github.com/superhighfives/pika/releases/tag/0.0.8-beta2
