### ISSUE TITLE
Making all of the data captured more easily available - at point of capture and later

### ISSUE THREAD

**Issue by lloydi** [superhighfives/pika#42]
So, I've been mulling over some things. I think you could add a killer feature ... or it'd be a killer feature for me! :D 

Let me explain my process with this sort of tool:

While auditing a site, I grab screenshots of issues found. For color contrast, I might use Chrome Dev tools and the screenshot will include the foreground, background color the ratio and the element being checked. I do the same with a separate color picker.

First phase of checking:

Pick the foreground color
Pick the background color
Move the color picker tool near to the element being checked
Fire up a screenshot app and capture relevant area
In the screenshot app, draw boxes around the color hex values, the contrast and the element being checked
Save the file

Later, when I come back to properly write up the issues, I refer back to my screenshots. For each image, I then have to open it, look at the highlighted figures, re-type them in the report. And so on, repeat, repeat, repeat.

One feature that I imagine would be quite easy to implement:

A 'copy all data' option that outputs something like:

Foreground: #XXXXXX
Background: #XXXXXX
The contrast ratio is: X:1
Text passed at Level AA
Text failed at Level AAA
Large text passed at Level AA
Large text failed at Level AAA

to the clipboard. You have all that data already. 

But for the absolute killer feature - include screenshot functionality with the app. User would still select the area to snap, which would include the PIKA app.

Now, you have all that data ... so you could also then suggest a filename that includes all that date, for example:

Appname-date-color1_000000-color2_ffffff-contrast_1.5-aa_fail-aalarge_pass-aaa_fail-aaalarge_pass.png

That way, the data is all there in the filename on save which could then be programatically retrieved later.

Image a collection of 20 files, all saved in this format. A macro could read all the file data and then transform that back to the data that I suggested could be output in the app.

Something to mull over?

**Comment by superhighfives** [comment]
Hey @lloydi. First off, thanks for detailing your use case so clearly, and for laying out your ideas for how Pika could better help you.

I think being able to copy all data is an interesting idea, especially for those kinds of auditing use cases. Though I think implementing it could be relatively straightforward, it's not something that has come up in my conversations with people who are using Pika, so I'm not sure how common the use case is—I'm reluctant to add additional overhead to the app for fear of overcomplicating in, so I'd love to leave this issue open to see if others come across it and ask for the same.

For the second aspect, [one of the principles I've had for Pika](https://github.com/superhighfives/pika/wiki) is that it doesn't ask for permission to record the screen—it's a bit of a pain, and the trust aspect needs to be explained to users (why does this app want to record my screen, for example)—so I've avoided that by using Apple's NSColorSampler API which doesn't have the same requirement for permissions. I can't see a way to do this without implementing screen capture, which feels different enough from the underlying use cases that it would likely make sense to fork the project—I think it could be a great idea for auditing, but I don't believe it's right for Pika itself.

Will leave this issue over and see whether anyone else has similar needs, and again, appreciate your input! 🙌

**Comment by lloydi** [comment]
Ah yes, I remember about the asking permission thing. Gotcha.

That said, an additional menu item - just one incy-wincy menu item - that allowed 'Copy all color contrast data' wouldn't take up *that* much room (twists arm, winks).

I realise that my use case was quite specific, always worth a shout :)

**Comment by superhighfives** [comment]
😊

Yeah, I'm currently simplifying the menus, too. One thought is format—would it be human or machine readable? For example:

```
Foreground: #XXXXXX
Background: #XXXXXX
The contrast ratio is: X:1
Text passed at Level AA
Text failed at Level AAA
Large text passed at Level AA
Large text failed at Level AAA
```

Or should this be in an easier to process format like JSON?

```
{
  "colors": {
    "foreground": "#XXXXXX",
    "background": "#XXXXXX"
  },
  "ratio": "XYZ",
  // ...etc
}
```

Currently prepping `0.0.10`, which covers #19 and #20, but will have a proper look at this one following that.

**Comment by lloydi** [comment]
> Yeah, I'm currently simplifying the menus, too. One thought is format—would it be human or machine readable? For example:

I would say human-readable. The suggestion I had about having the data in a machine-readable format was specifically for the screenshot filename, if it were possible to include screenshot functionality. But for the menu copy data, I'd say human-readable :)

**Comment by superhighfives** [comment]
Started a branch on this one:
https://github.com/superhighfives/pika/tree/simplify-menus

Going to focus on getting 0.0.10 out, but keen to look at this and #50 as part of 0.0.11.

**Comment by superhighfives** [comment]
Tackled this as part of the 0.0.11-beta1 release, which is available now: https://github.com/superhighfives/pika/releases/tag/0.0.11-beta1

Let me know what you think, and thanks for flagging. 🙌

**Comment by superhighfives** [comment]
Awesome, this is now live in v0.0.11. 🥳 https://github.com/superhighfives/pika/releases/tag/0.0.11
