### ISSUE TITLE
Move shortcuts to Preferences

### ISSUE THREAD

**Issue by ovanbiervliet** [superhighfives/pika#44]
The shortcut settings that are now (0.0.9) on the About dialog are virtually undiscoverable. I would think they belong to the Preferences screen 😉

**Comment by superhighfives** [comment]
Yeah, I can see your point @ovanbiervliet—the preferences are definitely a more likely path for someone to take, but as the keyboard shortcuts aren't editable, and they're displayed in the menu, I'm keen to keep the preferences purely for settings, while About is informational.

Appreciate you flagging!

![A screenshot of Pika showing the menu with shortcuts displayed](https://user-images.githubusercontent.com/449385/108594373-9f893480-7371-11eb-91e4-67943ec7ecbe.png)
