### ISSUE TITLE
Make the 'lens' outline more visible

### ISSUE THREAD

**Issue by lloydi** [superhighfives/pika#45]
Simple one here - when picking a colour, the outline of the lens (or whatever you call it) is *VERY* difficult to see. Given that this picker puts colour contrast front and centre, it would be good if the outline shown here was more obvious and passed WCAG [SC 1.4.11 Non-text Contrast](https://www.w3.org/TR/WCAG21/#non-text-contrast).

<img width="329" alt="SCR 2021-02-21 at 10 40 04" src="https://user-images.githubusercontent.com/2778763/108623444-0ae90a00-7437-11eb-89fd-f6390e6179ca.png" alt="">

**Comment by lloydi** [comment]
I'm not a designer, but thinking something that is slightly thicker and which has a darker and ligher ring would help. Of course, when you're over a busy area of the screen, the content showing through will be magnified and therefore the outer ring is easier to perceive. It's only difficult to perceive the ring and the inner square when hovering over a plain(ish) background.

<img width="254" alt="Screenshot_2021-02-21_at_11_28_24" src="https://user-images.githubusercontent.com/2778763/108623759-8dbe9480-7438-11eb-8a04-13d51778e1d1.png" alt="Slightly bolder lens ring">

**Comment by superhighfives** [comment]
Yeah, it's a shame there are so few customisation options for the NSColorSampler API that Apple provides for colour picking. As shown in the docs, it's only got the simple function to initialise, and no options:
https://developer.apple.com/documentation/appkit/nscolorsampler

The alternative would be to roll a custom colour picker, but that requires screen recording privileges, which is outside the scope of this app. I'm hoping in future Apple opens up hooks to add additional functionality (showing the value while picking on the picker itself, for example) and to customise the picker itself, but currently it's not possible.

Thanks for flagging, @lloydi, and for the mock up. Appreciate it! If you're interested in flagging this to Apple, you can do so here: https://developer.apple.com/bug-reporting/

Related issue: #8
