### ISSUE TITLE
Global shortcut can’t have Control + Alt + Command

### ISSUE THREAD

**Issue by rileyjshaw** [superhighfives/pika#49]
Hi! I’m excited to start using this app, thanks for making it.

I just tried to set my global shortcut on the initial screen (and later from the preferences menu) to `Control + Alt + Command + P`. It won’t allow that combo.

**To Reproduce**
1. Install (or open) Pika
2. Try to set the “Global Shortcut” to `Control + Alt + Command + P`.

**Expected behavior**
The shortcut should stick.

**Observed behavior**
✅ `Control + Alt + P`
✅ `Control + Command + P`
✅ `Alt + Command + P`
✅ `Shift + Alt + Command + P`
❌ `Control + Alt + Command + P`
✅ `Shift + Control + Alt + Command + P`

**Environment (please complete the following information):**
 - OS: MacOS Big Sur
 - App Version: 11.1 (20C69)
 - Architecture: 3.3 GHz Dual-Core Intel Core i7

Thanks!

**Comment by superhighfives** [comment]
Hey @rileyjshaw. Thanks for the kinds words, and for checking Pika out.

Hmmm, tried it out successfully on my machine—I've attached an image:

![image](https://user-images.githubusercontent.com/449385/109730000-ac4b2b00-7bb0-11eb-9e24-97bdc8b4247b.png)

The only reason I can see that it wouldn't work is if it's clashing with another global shortcut you have set up on your machine. I'm using https://github.com/sindresorhus/KeyboardShortcuts under the hood, which also mentions there are some reserved shortcuts, too: https://github.com/sindresorhus/KeyboardShortcuts/issues/33

You should also get a warning if it's already a system-wide one (outside of another global you've set) like the example below:

![image](https://user-images.githubusercontent.com/449385/109730273-28457300-7bb1-11eb-8ebe-6655cfb80829.png)

Going to close this one, but let me know if you find the culprit. 👍  Thanks for flagging!

**Comment by rileyjshaw** [comment]
<img width="271" alt="image" src="https://user-images.githubusercontent.com/1840854/109905307-6f844000-7c53-11eb-858e-cce59d257030.png">

Well, I haven’t found the culprit for `P` yet… but other Control + Alt + Command shortcuts DO work. Thank you for the great explanation, makes perfect sense!
