### ISSUE TITLE
Real-time swatch update while picking a color

### ISSUE THREAD

**Issue by meduzen** [superhighfives/pika#51]
While we’re hovering another color in search for another color, the swatch stays the same.

It would be very handy to receive instant feedbacks (color + values + contrast ratio) while hovering the screen. Real-time data will speed up decision processes based on color comparison and WCAG compliance.

**Comment by superhighfives** [comment]
Hey @meduzen. Unfortunately this is a limitation of the underlying Apple-provided API, NSColorSampler. You can learn a little more about it (and, if you're keen, request Apple add additional functionality) here: https://github.com/superhighfives/pika/issues/45#issuecomment-782846224

Going to close this one as it's outside the scope of the app, currently, but fingers crossed it'll be possible one day. Thanks for flagging.
