### ISSUE TITLE
Add preferences shortcut (cmd ,) to menu

### ISSUE THREAD

**Issue by ovanbiervliet** [superhighfives/pika#54]
As the title says, the shortcut for preferences works but is not mentioned in the menu.

<img width="206" alt="CleanShot 2021-03-03 at 11 59 39@2x" src="https://user-images.githubusercontent.com/3488544/109796028-f4e9ff00-7c17-11eb-8bfa-8bc9eb5d6cb6.png">

**Comment by superhighfives** [comment]
Ah, good catch! Added to https://github.com/superhighfives/pika/commit/d7d1ec30b2baad794978e8b914f96cc531521592, which will ship with v0.0.10. Thanks @ovanbiervliet. 🙌

**Comment by superhighfives** [comment]
Great, you can try this out in `v0.0.10-beta2` by checking "Subscribe to beta updates" in preferences and checking for updates. 🙌
