### ISSUE TITLE
Missing shortcuts upon launch

### ISSUE THREAD

**Issue by ovanbiervliet** [superhighfives/pika#55]
When Pika is first launched, the shortcuts are not mentioned in the cog menu. 

![CleanShot 2021-03-05 at 12 48 39](https://user-images.githubusercontent.com/3488544/110112007-76c16000-7db1-11eb-9151-1b56a66c5168.png)

Afterwards they are present:
![CleanShot 2021-03-05 at 12 49 17](https://user-images.githubusercontent.com/3488544/110112071-8640a900-7db1-11eb-8cac-8f158c4e6fed.png)

0.0.10 beta 2

**Comment by superhighfives** [comment]
Yeah, this one seems to be a bug in MacOS / Big Sur, which I was hoping would be resolved in a new version. If anyone has any idea how to fix this, I'd love to hear it. There was a similar issue on the gear icon (being low opacity until clicked) which I was able to fix by hiding / showing it with a timer, but I've been unable to find a fix for the shortcuts.

If you right click the Pika icon, you'll see that preferences has the shortcut straight away, so it seems to be a bug in `Menu`.

**Comment by ovanbiervliet** [comment]
I did not find anything like this, nor have I experienced it with any other app so far. Are you sure this is caused by Big Sur?

**Comment by superhighfives** [comment]
Yeah, I think the potentially "uncommon" thing is that I'm using `NSWindow` with `NSHostingView`, to display a SwiftUI component inside of the toolbar. That's required for it to work with 10.15. I've tried displaying it directly using `.toolbar`, but it doesn't seem to play nice with `NSWindow`, which is, again, a requirement for macOS 10.15.

Keyboard modifiers being defined in SwiftUI only works in 11, too, which further complicates things.

I'd love if anyone knows of a solution, though, or if anyone else has come across this. There may be something else causing it, but I haven't been able to pinpoint it.

**Comment by ovanbiervliet** [comment]
Outside of my expertise 😅 the closest I got was Swift. Does this article contain any revelations? https://izziswift.com/how-do-i-add-a-toolbar-to-a-macos-app-using-swiftui/

**Comment by superhighfives** [comment]
Yeah, that's pulled from https://stackoverflow.com/questions/60464925/how-do-i-add-a-toolbar-to-a-macos-app-using-swiftui, which I've tried previous, but 10.15 compatibility / using NSWindow appears to be the underlying issue. 😞

**Comment by superhighfives** [comment]
Going to close this one as it's a Big Sur issue, but happy to reopen if anyone has any ideas on a solution.
