### ISSUE TITLE
Make the text values selectable, and editable, so you can compare colours without the picker

### ISSUE THREAD

**Issue by superhighfives** [superhighfives/pika#57]
**Is your feature request related to a problem? Please describe.**
Currently it's impossible to tweak or change colours.

**Describe the solution you'd like**
Make the text values selectable, and editable, so you can compare colours without the picker.

**Describe alternatives you've considered**
This may be too complex for [Pika's core product vision](https://github.com/superhighfives/pika/wiki), especially given the overhead of validating the text inputs, the different formats, etc. So one alternative is to not do this.

**Additional context**
This was initially detailed in #19.

**Comment by lloydh** [comment]
👍 I would love to see this to make Pika a go-to colour utility. I often find myself launching Photoshop just to try adjusting the HSL values of a colour. Undo/redo before/after history would be great too.

**Comment by superhighfives** [comment]
Just flagging the issue for undo / redo / color history is here: #26.

I also mentioned [on this comment](https://medium.com/@superhighfives/hey-thanks-for-the-kind-words-in-your-other-response-8667dcc7257d?source=responses-----d7725c397585----0----------------------------) some thoughts on the scope of the app, and potentially spinning it off to be a bigger app beyond just the color picking utility, because I don't want to make things too complex given [my original goals](https://github.com/superhighfives/pika/wiki):

> For the window in the foreground, Pika is intended to be a utility rather than an app, which is why it functions that way (macOS has a limited number of window "types"). That said, as I look at more complex use cases I've been thinking about whether it would make sense to spin off a document-style app to better handle things like history and more complex colour accessibility / APCA support.

**Comment by ScottAgirs** [comment]
I was about to create a feature request for this.

Hey folks! Awesome job on Pika - loving it 3000 so far!

The only thing missing for me is the option to edit the color.
I need to launch another app just to do this, which is a big-big bummer.

Would absolutely love to see this implemented as well, then it would be the hands down best colour utility for macOS in my exp.! :) 🙌🏼

**Comment by superhighfives** [comment]
Yeah, absolutely. If someone is interested in taking a pass at it, I'd love to see how they might approach it. It's definitely on my list, but I can't be certain I'll get to it anytime soon, especially given it's a big change that introduces a lot of edge cases.

**Comment by ronilaukkarinen** [comment]
Sorry to bump this, but any progress? I use Pika daily at work so this would be nice to have in some point. I'd glad to help but unfortunately Swift is not my area of expertise.

**Comment by superhighfives** [comment]
No worries at all. I'm currently not able to commit to it (and I'm currently focused on getting Pika v0.0.13 out the door), but as always, would love to check out a PR if someone was interested in taking a pass at it.

**Comment by ronilaukkarinen** [comment]
Cool, thanks for the info. 👍

**Comment by superhighfives** [comment]
While I'd love to implement it, this currently remains out of scope—I'd recommend checking out https://colorslurp.com/ or https://sipapp.io/, which are more fully featured colour pickers and may be a better fit for this use case.

**Comment by yougotwill** [comment]
@superhighfives Does https://github.com/superhighfives/pika/issues/125 solve this issue since you can enter the color manually in the system color picker?

**Comment by superhighfives** [comment]
Indeed it does! It's currently in beta, but you can grab it via the app or at https://github.com/superhighfives/pika/releases/tag/0.0.18-beta2. See more on #125.
