### ISSUE TITLE
Option to display as HSL

### ISSUE THREAD

**Issue by connorlindsey** [superhighfives/pika#6]
**Is your feature request related to a problem? Please describe.**
HSL is a very popular color format and I think would be a great addition to the app. 

**Describe the solution you'd like**
Additional option in settings to display as HSL. 

**Describe alternatives you've considered**
Right now, I'm using HEX and could convert the color to HSL online.

**Additional context**
Not sure how the app is built, but I'm guessing this would be a pretty small change. I may try to open a PR although I'm not familiar with Swift.

**Comment by superhighfives** [comment]
Hey @connorlindsey—yeah, that seems super straightforward, and definitely worthwhile. Added to the roadmap.

**Comment by connorlindsey** [comment]
Awesome, thanks for the quick reply!

**Comment by smlombardi** [comment]
Yes, for CSS we use HSL not HSB.

**Comment by superhighfives** [comment]
Hey @connorlindsey @smlombardi @meduzen—this is now available in the latest beta, 0.0.8-beta1. You can download it here:
https://github.com/superhighfives/pika/releases/tag/0.0.8-beta1

I'd really appreciate it if you could check it out and let me know if you see any issues. (And if you do, you can always fall back to the latest stable version.) HSL is in the preferences menu, and there additional keyboard shortcuts—⌘D and ⇧⌘D to trigger the foreground and background picker, and ⌘C and ⇧⌘C to copy the foreground and background, respectively.

**Comment by meduzen** [comment]
All fine for me 👍 :
- HSL
- all shortcuts of your previous message.

**Comment by superhighfives** [comment]
Awesome. Just to flag, there's a bug with 0.0.8-beta1 where the footer won't update. Fixed in 0.0.8-beta2. You can either enable beta updates and check for updates in the app, to grab it here: https://github.com/superhighfives/pika/releases/tag/0.0.8-beta2

**Comment by connorlindsey** [comment]
Awesome, this is great! Thanks
