### ISSUE TITLE
Add keyboard shortcuts for fg/bg pickers

### ISSUE THREAD

**Issue by ovanbiervliet** [superhighfives/pika#7]
There is a shortcut to open Pika, but a direct shortcut to launch the foreground and background pickers would save a lot of time.

**Comment by superhighfives** [comment]
Thinking about this one today—should be pretty straightforward to have shortcuts to initialise `NSColorSampler`. Any thoughts on what those shortcuts should be as default @ovanbiervliet? Alternatively, they could be set as global shortcuts, but I think I prefer the idea of there being a single global shortcut you define, and then standard / preset keyboard shortcuts for launching the colour picker, copy, preferences, etc.

**Comment by ovanbiervliet** [comment]
Having just 1 global shortcut to open Pika is enough I guess. Something with an F and a B seems a good starting point?

**Comment by superhighfives** [comment]
Hey @ovanbiervliet—this is now available in the latest beta, 0.0.8-beta1. You can download it here:
https://github.com/superhighfives/pika/releases/tag/0.0.8-beta1

I'd love it if you could check it out and let me know if you see any issues. The shortcuts are ⌘D and ⇧⌘D to trigger the foreground and background picker, and ⌘C and ⇧⌘C to copy the foreground and background, respectively.

**Comment by superhighfives** [comment]
Ah, spoke too soon—there's a bug with 0.0.8-beta1 where the footer won't update. Fixed in 0.0.8-beta2. You can either enable beta updates and check for updates in the app, to grab it here: https://github.com/superhighfives/pika/releases/tag/0.0.8-beta2
