### ISSUE TITLE
Hide Pika when launch at login

### ISSUE THREAD

**Issue by fharper** [superhighfives/pika#72]
It would be nice to have an option to automatically hide the main Pika window when it is automatically launch at login

**Comment by superhighfives** [comment]
Hey @fharper—which version of Pika are you using? Also, are you able to screenshot the preferences screen and the settings dropdown?

It should be hidden when automatically launched at login, so I'd be keen to try and recreate this. Thanks for flagging too. 👍

**Comment by fharper** [comment]
So sorry, that was a shitty issue: I added NO informations whatsoever!

I use v0.0.12 build 23, and here is the preferences window

<img width="552" alt="CleanShot 2022-01-05 at 09 29 25@2x" src="https://user-images.githubusercontent.com/1170989/148234191-e03a8910-18a8-4a89-bbdb-6b9862683ee3.png">

Also, not sure why, but now it's not happening anymore!!! So I'm closing this issue, and thanks for the fast reply & this great OSS.

**Comment by superhighfives** [comment]
No worries at all, @fharper—let me know if it rears it head again in future, and thanks so much for the kind words. Appreciate it. 😊
