### ISSUE TITLE
Colours formatted for CSS

### ISSUE THREAD

**Issue by MMMikeM** [superhighfives/pika#74]
It'd be really nice if we were able to have an option to allow pre-formatted colours, specifically for HSL

[MDN Docs on the topic](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl())

Currently, HSL is copied in the format ```hsl(0, 0, 0)```, it would be ideal to have an option in the preferences that would preformat it as ```hsl(0, 0%, 0%)``` as this would improve workflow for developers.

### General Settings
- [X] Launch at login
- [ ] Hide menu bar icon
- [ ] Hide color names
- [X] Subscribe to beta releases
- [X] Format for CSS

It's a pretty minor change, but I've been loving Pika and this would make it even more enjoyable to use!

**Comment by superhighfives** [comment]
Hey @MMMikeM—thanks for flagging. I wonder if this should be the paired with "hide format when copying"? 🤔

<img width="303" alt="image" src="https://user-images.githubusercontent.com/449385/153568874-06f7c5f9-c895-4b97-b0a3-1c26f3b8f59c.png">

For example, moving this into the settings as a dropdown with:

**General settings:**

- Export format
  - Format for design applications
  - Format for CSS

- [ ] Hide formatting on export

I also wonder if the first two options in the dropdown should move into the settings, too. Settings are a little confusing in that they exist in both the dropdown and the settings menu.

Curious to get feedback, too!

**Comment by MMMikeM** [comment]
That's an excellent point. Thinking about this, I feel as though usage
frequency could be a determining factor and adjacent to this, whether the
option has a shortcut or not.

How frequently do you think the hide format option is toggled?

I do have a bias towards fewer options in the context/drop down menu, so
gotta try argue against myself here 😂

**Comment by MMMikeM** [comment]
Amazing, really looking forward to it!

**Comment by superhighfives** [comment]
Awesome, took my sweet time, but got a fancy shiny beta for you to check out, @MMMikeM:
https://github.com/superhighfives/pika/releases/tag/0.0.13-beta1

You can also get it by checking for updates in the app (just make sure "subscribe to beta releases" is enabled in the preferences). I tidied up the preferences pane, consolidated the menu items, and added the export / copy settings option for CSS, design applications, and unformatted. Looking forward to hearing your thoughts and feedback, and thanks for the encouragement.

There are some known issues with preferences and the window display when the language is set to French, so will resolve that before release.

**Comment by MMurrayDVT** [comment]
This is great, wow!!  I like the changes to the preferences page and this option is a huge help for devs.

Thanks to much for adding this!

**Comment by superhighfives** [comment]
Awesome, thanks @MMMikeM! Really appreciate it.

The issues are all sorted on the French language display and have been released as part of `0.0.13-beta2`, but let me know if you have any other feedback. Aiming to release it later this week.

**Comment by superhighfives** [comment]
Sweeeeet, this is now live. 👍
