### ISSUE TITLE
Show color value near picker

### ISSUE THREAD

**Issue by ovanbiervliet** [superhighfives/pika#8]
When using the picker I'd like to see the value that I'm going to pick near the cursor, instead of switching my focus to the Pika window.
<img width="246" alt="CleanShot 2021-01-16 at 16 47 59@2x" src="https://user-images.githubusercontent.com/3488544/104816317-a674d280-581a-11eb-8d04-e4f81f671089.png">

**Comment by superhighfives** [comment]
I'd love to add this, but currently it appears to be a limitation on the macOS side. I'm using the [NSColorSampler](https://developer.apple.com/documentation/appkit/nscolorsampler) class, which bypasses the need for the user to give the app permission to record this screen. If anyone has an example of extending the functionality of NSColorSampler to add a text overlay, I'd love to check it out.

**Comment by superhighfives** [comment]
Going to close this for now, given the limitations of the API, but it's currently in the [Icebox in the GitHub project](https://github.com/superhighfives/pika/projects/1) for future reference.
