### ISSUE TITLE
WCAG AA normal size shown (rather than AA large)

### ISSUE THREAD

**Issue by joeledge** [superhighfives/pika#80]
**Is your feature request related to a problem? Please describe.**
Most often I need to check WCAG contrast for text at normal size, Pika only shows AA Large

**Describe the solution you'd like**
Show WCAG compliance for AA normal size rather than just large

**Describe alternatives you've considered**
Preferences to allow what is show in the bottom WCAG Compliance area to be customised

**Comment by joeledge** [comment]
Thanks for responding! I could definitely use knowing that, personally I find it a little confusing as am used to seeing 'Normal' or 'Large' so I don't think I'd assume that without knowing prior it was for normal. 

Perhaps something like this?

<img width="640" alt="Screenshot 2022-05-19 at 14 32 12" src="https://user-images.githubusercontent.com/28432913/169305583-9fd7c815-6167-4aec-b920-c4ffa957bf5b.png">

**Comment by superhighfives** [comment]
No worries at all, and appreciate the suggestions. Been noodling on it a little on this PR:
https://github.com/superhighfives/pika/pull/81

**Comment by superhighfives** [comment]
Sweeeeeet—got a new beta for you to check out, @joeledge. Added it as an appearance preference in the preferences, and defaulted to the new style as I agree it's easier to understand at a glance. Let me know what you think (to check out a beta, download it from here, or enable betas in Preferences and click "Check for updates" in the menu.

<img width="1174" alt="Pika v0.0.13-beta app screenshot" src="https://user-images.githubusercontent.com/449385/172071438-aba27fdd-7845-488b-a396-c564572d1469.png">

**Comment by joeledge** [comment]
Awesome, that works brilliantly for me. Thanks for taking the time to work on this issue!

<img width="973" alt="Screenshot 2022-06-06 at 09 07 28" src="https://user-images.githubusercontent.com/28432913/172121727-4a8f58bc-2843-4fa8-a1de-1c6888c14747.png">
.
