### ISSUE TITLE
Show the color value while while picking the color

### ISSUE THREAD

**Issue by nonameplum** [superhighfives/pika#87]
**Is your feature request related to a problem? Please describe.**
It would great if we could see the value of the color realtime while picking the color, something that e.g. SIP has https://sipapp.io/assets/img/home/contrast-checker.mp4

**Describe the solution you'd like**
The color could be presented like in SIP close to the magnifier.

**Describe alternatives you've considered**
Close the color realtime in the Pika window, but as there is already an option to hide the Pika window while picking the color probably not the best solution.

**Additional context**
Easier to quickly verify the color.

**Comment by superhighfives** [comment]
I'd love to do this, but currently it's a limitation of the [Apple API I'm using to do the colour picking](https://developer.apple.com/documentation/appkit/nscolorsampler), and building it manually is out of scope. I hope they add some more customisation features in future.

You can learn more here, too / related issue: https://github.com/superhighfives/pika/issues/45#issuecomment-782846224
