### ISSUE TITLE
Show color code

### ISSUE THREAD

**Issue by TigerCat-hu** [superhighfives/pika#90]
How to show color code if I use color picker tool?

![color_code](https://user-images.githubusercontent.com/33827733/207052636-b2a109c1-b0d6-4417-b12c-1ab8087640ab.jpg)

**Comment by superhighfives** [comment]
I'd love to do this, but currently it's a limitation of the [Apple API I'm using to do the colour picking](https://developer.apple.com/documentation/appkit/nscolorsampler), and building it manually is out of scope. I hope they add some more customisation features in future.

You can learn more here, too: https://github.com/superhighfives/pika/issues/45#issuecomment-782846224
