### ISSUE TITLE
Color pallets

### ISSUE THREAD

**Issue by gldtn** [superhighfives/pika#94]
Allow to create color pallets and/or favorite colors 😁

**Comment by superhighfives** [comment]
Thanks for taking the time to write up an issue. Currently I think more complex colour management is out of scope for this app (and there are a couple of apps that already do a great job like [Sip](https://sipapp.io/) and [Color Slurp](https://colorslurp.com/)). 

That said, if anyone is keen to put forward an implementation I'd love to check out a PR.

**Comment by superhighfives** [comment]
(There is some similar discussion on this here, too: https://github.com/superhighfives/pika/issues/65)
