### ISSUE TITLE
Create colour palette

### ISSUE THREAD

**Issue by vikashsurin** [superhighfives/pika#97]
**Feature Request**
### **Ability to create Color Palette**

1. I am ux designer. And recently I had a task to redesign a website while keeping the existing colour theme. So I started picking colours in pika and was limited to choose 2 colours at a time. 

2.  **Sol:** What if I could choose all the colours one by one and create a palette out of it at one go, and straight away import the colour palette in the design software, like figma. This could increase efficiency and reduce frustation of the Pika user.

**Comment by superhighfives** [comment]
Hey @vikashsurin—thanks taking the time to reach out and make this suggestion. While I'd love to add features like colour themes and import / export, colour tweaking, and more robust colour management, it's currently out of scope. I do think a bunch of apps do a great job of this, like https://sipapp.io/ or https://colorslurp.com/, so for the time being I've opted to keep Pika as simple as possible.

Thanks again for reaching out! 😊
